name: Docker CICD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cicd-docker:
    name: CICD Docker
    runs-on: ubuntu-latest
    steps:
      - name: Docker build and publish
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: sakadream/rust-wasm
          add-git-labels: true
          tag_with_ref: true